name: Eamon Niknafs
favicon: null
layout_spectrum: 0.49364
typography_spectrum: 0.13796
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0a2029'
    - '#567b9d'
    - '#58483a'
    - '#949b99'
    - '#bdc2c1'
  brandStrength: 0
  lightness: 0.6875
  saturation: 0
  rhythmicContrast: 1
purpose: []
