name: Eamon Niknafs
favicon: null
layout_spectrum: 0.49364
typography_spectrum: 0.13796
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ff6b21'
    - '#234453'
    - '#2bc0a2'
    - '#878b58'
    - '#ffb32a'
  brandStrength: 0
  lightness: 1
  saturation: 0
  rhythmicContrast: 1
purpose: []
